# Generated by Django 6.0.4 on 2026-04-20 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المؤلف')),
                ('bio', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='صورة المؤلف')),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفون',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-book', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='صورة الغلاف')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books_pdf/', verbose_name='ملف PDF')),
                ('read_online_url', models.URLField(blank=True, verbose_name='رابط القراءة online')),
                ('published_year', models.IntegerField(verbose_name='سنة النشر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للعرض')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه من الإدمن')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
                ('reads_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='المؤلف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الذي رفع الكتاب')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'كتاب مفضل',
                'verbose_name_plural': 'الكتب المفضلة',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
